# Generated by Django 5.0.6 on 2024-07-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_is_admin'),
    ]

    operations = [
    ]
