# Generated by Django 5.0.6 on 2024-07-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_boolen_field'),
    ]

    operations = [
    ]
