# Generated by Django 5.0.6 on 2024-07-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_comment_image_comment_image_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='users.geo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
