# Generated by Django 5.0.6 on 2024-07-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_address_geo_alter_address_zipcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'permissions': [('edit_todo', 'Can edit todo')]},
        ),
    ]
