# Generated by Django 5.0.6 on 2024-07-12 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
